import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0a1120",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  form: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#151f33",
    borderRadius: 20,
    padding: 28,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  logo: {
    fontSize: 50,
    textAlign: "center",
    marginBottom: 10,
    color: "#3690fdff",
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#e6eef8",
    textAlign: "center",
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 15,
    color: "#9baec8",
    textAlign: "center",
    marginBottom: 24,
  },
  input: {
    backgroundColor: "#1f2b40",
    color: "#fff",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    fontSize: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#2f3d57",
  },
  button: {
    backgroundColor: "#007bff",
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 8,
    shadowColor: "#007bff",
    shadowOpacity: 0.4,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  buttonDisabled: {
    backgroundColor: "#4c6fa3",
    shadowOpacity: 0,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 17,
  },
  toggleText: {
    color: "#8faadc",
    textAlign: "center",
    marginTop: 18,
    fontSize: 15,
  },
  error: {
    color: "#ff6b6b",
    textAlign: "center",
    marginBottom: 8,
    fontSize: 14,
  },
  backButton: {
    marginTop: 24,
    alignItems: "center",
  },
  backButtonText: {
    color: "#9bb3e0",
    fontSize: 16,
    textDecorationLine: "underline",
  },
});
